apiVersion: batch/v1
kind: Job
metadata:
  name: create
spec:
  template:
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: my-files-claim
      containers:
      - name: create
        image: doubleho/store:create
        env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_PASSWORD
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: PORT

        volumeMounts:
        - name: shared-files
          mountPath:  /app/ft
      restartPolicy: Never # This time we'll run it only once