apiVersion: batch/v1
kind: CronJob
metadata:
  name: extract
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes: 
            - name: extracted-files
              persistentVolumeClaim:
                claimName: ext-claim

          containers:
          - name: extract
            image: doubleho/store:extract
            env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_PASSWORD
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: PORT

            volumeMounts:
            - name: extracted-files
              mountPath: /app/extracted
          restartPolicy: OnFailure