apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: my-files-claim
      containers:
        - name: transactions
          image: doubleho/store:transaction
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_PASSWORD
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: PORT

          volumeMounts:
          - name: shared-files
            mountPath: /app/ft